version: '3.8'

services:
  mainsite:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/gdg
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - gdg-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - gdg-network

networks:
  gdg-network:
    driver: bridge

volumes:
  mongodb_data: 