version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - gdg-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/gdg
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - gdg-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - gdg-network

networks:
  gdg-network:
    driver: bridge

volumes:
  mongodb_data: 